name: Bump version

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - prerelease
  push:
    branches:
      - prerelease

permissions:
  contents: write

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'push' && github.ref || github.event.pull_request.base.ref }}
        fetch-depth: '0'
        fetch-tags: true

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_PREFIX: v
        PRERELEASE: true
        